name       : kdegraphics-thumbnailers
version    : 18.04.3
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kdegraphics-thumbnailers-18.04.3.tar.xz : aae09cd604c0a18ceca00555254972d4816e00bd6c427531ed7a447860750ddd
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
