name       : kdegraphics-thumbnailers
version    : 19.08.3
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kdegraphics-thumbnailers-19.08.3.tar.xz : 14d342336e92b3913d46a415da9fcf53d239f0ceb16aed99c1e095641ce6ddb4
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
