name       : kdegraphics-thumbnailers
version    : 19.08.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/kdegraphics-thumbnailers-19.08.0.tar.xz : 127a99fffdaee3772b03a6c197357311ec56047caccce967f0d74b5489722ddf
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
