name       : kdegraphics-thumbnailers
version    : 22.04.3
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kdegraphics-thumbnailers-22.04.3.tar.xz : 3fb892a96978bd6198cd9a4b04f8b74205917401b915dca722d945a820ca9c36
homepage   : https://apps.kde.org/kdegraphics_thumbnailers/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - karchive-devel
    - kdegraphics-mobipocket-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
