name       : kdegraphics-thumbnailers
version    : 18.08.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kdegraphics-thumbnailers-18.08.0.tar.xz : 5c46dbef24864a644d0fc5854e29f1676b8ed151cd759bd4200f78703ebc8e37
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
