name       : kdegraphics-thumbnailers
version    : 20.08.1
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kdegraphics-thumbnailers-20.08.1.tar.xz : 8303231f2fc44c071b3f6a477ae5335f2657dbfaba52362529aaba20973a5995
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-thumbnailers
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kio-devel
    - kwindowsystem-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
