name       : kdegraphics-thumbnailers
version    : 23.04.1
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kdegraphics-thumbnailers-23.04.1.tar.xz : 4511d37ddb6ab98f744a0a3b208d6d74ba71aa1dd1dc2db3d513ca39de6be3ae
homepage   : https://apps.kde.org/kdegraphics_thumbnailers/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - karchive-devel
    - kdegraphics-mobipocket-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
