name       : kdegraphics-thumbnailers
version    : 18.12.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kdegraphics-thumbnailers-18.12.0.tar.xz : e426263fa515ab5da122114e9116609497debcf49614e5341a620253be66ca24
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
