name       : kdegraphics-thumbnailers
version    : 18.04.2
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kdegraphics-thumbnailers-18.04.2.tar.xz : 74f9c3fdae91d1e79e31322b31cae36bcd72e71c109589ee3bb56180da20aad8
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
