name       : kdegraphics-thumbnailers
version    : 21.04.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/kdegraphics-thumbnailers-21.04.0.tar.xz : a02c9a94ff6d5dfd0d5c3b8074aee70e10cef4e08541283057effe33d425ea79
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-thumbnailers
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - karchive-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
