name       : kdegraphics-thumbnailers
version    : 21.08.3
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kdegraphics-thumbnailers-21.08.3.tar.xz : e5d9dcc31c53551e79b4ee6024529ec6fbf6282b740df2698877aceae5ac72c1
homepage   : https://apps.kde.org/kdegraphics_thumbnailers/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - karchive-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
