name       : kdegraphics-thumbnailers
version    : 21.08.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kdegraphics-thumbnailers-21.08.2.tar.xz : e2a090b49319aea7dee072a683bffb97a4968f2e8b2586b58e990ae5889dc188
homepage   : https://apps.kde.org/kdegraphics_thumbnailers/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - karchive-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
