name       : kdegraphics-thumbnailers
version    : 20.04.2
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/kdegraphics-thumbnailers-20.04.2.tar.xz : e20017679559395dd33fdc744bd1e40416349be91c8ed1b12e4c0c398bfbcecf
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-thumbnailers
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kio-devel
    - kwindowsystem-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
