name       : kdegraphics-thumbnailers
version    : 22.08.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kdegraphics-thumbnailers-22.08.3.tar.xz : 3d0496a25dd292b4c6e2caef934be5b84b2f5bcfbdbf87e5c819d62d88dead73
homepage   : https://apps.kde.org/kdegraphics_thumbnailers/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - karchive-devel
    - kdegraphics-mobipocket-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
