name       : kdegraphics-thumbnailers
version    : 22.04.1
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kdegraphics-thumbnailers-22.04.1.tar.xz : 1706ae5b009cd79c95674ed8fdfb48f6206948cdd280b59074ce7f55b29c19f9
homepage   : https://apps.kde.org/kdegraphics_thumbnailers/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - karchive-devel
    - kdegraphics-mobipocket-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
