name       : kdegraphics-thumbnailers
version    : 18.12.1
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kdegraphics-thumbnailers-18.12.1.tar.xz : 72d77b2702ef8dd11efe4451daa77eb2da003a6bd2923687a8235bf31b3ae5e7
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
