name       : kdegraphics-thumbnailers
version    : 20.12.3
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kdegraphics-thumbnailers-20.12.3.tar.xz : dd598626c007145d20c4d32b648ee00bf9948d811dcd3d848df76c1195347f3c
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-thumbnailers
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Thumbnailers for various graphics file formats
description: |
    Thumbnailers for various graphics file formats.
optimize   : lto
builddeps  :
    - karchive-devel
    - kio-devel
    - libkdcraw-devel
    - libkexiv2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
